spring:
  profiles:
    active: windows

#——————————————windows——————————————
---
server:
  port: 8095
  servlet:
    context-path: /
spring:
  .profiles: windows
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jt.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.jt.mapper: debug

dubbo:
  scan:
    basePackages: com.jt  #扫描dubbo的注解
  application:
    name: provider-order   #定义服务的名称
  registry:
    address: zookeeper://192.168.146.130:2181?backup=192.168.146.130:2182,192.168.146.130:2183
  protocol:
    name: dubbo
    port: 20882